name: Build and deploy angular app

on:
  push:
    branches: [main]
env:
  FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}

jobs:
  build-and-deploy-angular-app:
    name: Build and deploy Angular app
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Angular app dependencies
        if: success()
        run: cd ./angular && npm install && cd ../

      - name: Build Angular app
        run: cd ./angular && npm run build --omit=dev && cd ../

      - name: Install Firebase CLI
        if: success()
        run: npm install -g firebase-tools@latest

      - name: Deploy to app Firebase hosting
        if: success()
        run: firebase deploy --only hosting
