name: Build and deploy firebase functions

on:
  push:
    branches: [main]
    paths:
      - firebase-functions/**

env:
  FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # The google service account credentials were written as an object in a .ts file.
      # the file was encoded in base64 and stored in a secret this all is to avoid problems
      # related to new line characters in the private key. Below we decode the base64 string
      # and reconstruct the credentials.ts file.
      - name: Decode Google service account credentials
        run: |
          echo ${{ secrets.CALENDAR_SERVICE_ACC_CREDENTIALS_BASE64 }} | base64 --decode > ./firebase-functions/credentials.ts

      - name: Install firebase functions dependencies
        if: success()
        run: cd ./firebase-functions && npm install && cd ../

      - name: Install Firebase CLI
        if: success()
        run: npm install -g firebase-tools@latest

      - name: Deploy Firebase functions
        run: firebase deploy --only functions
