name: publish-to-pages

on:
  push:
    branches: [master]
jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build --prod
      - name: Deploy to GitHub Pages
        if: success()
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: master
          FOLDER: dist/barber-service
