name: publish-to-pages

on:
  push:
    branches: [master]
  jobs:
    build:
      name: build
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v2
        - name: set up node
          uses: actions/setup-node@v1
          with:
          node-version: 18.x
